HazyResearch/meerkat

.github/workflows/ci.yml, mosaic/cells/volume.py, setup.py, tests/mosaic/cells/test_volume.py
Add support for `dosma.MedicalVolume` using the `MedicalVolumeCell`. This object is a lazy loader for medical images:
- loading is done with built-in data loaders
- key metadata information can be rolled out of the the medical image and accessed with `get_metadata()`
- `get()` returns a MedicalVolume when no transforms are specified
=> Update support for medicalvolume with dosma==0.0.13

mosaic/columns/abstract.py, mosaic/columns/cell_column.py, mosaic/columns/image_column.py, mosaic/columns/numpy_column.py, mosaic/columns/tensor_column.py, mosaic/datapanel.py, mosaic/mixins/materialize.py, mosaic/mixins/visibility.py, tests/mosaic/test_datapanel.py, tests/testbeds.py
`Column` and `Datapanel` no longer maintain state specifying whether cells should be materialized on `__getitem__` (_i.e._ `self._materialize` property no longer exists). Instead, if a user would like to index without materializing, they can use the `lz` indexer like: `dp.lz[0:3]`. 
Other changes:
- Added tests for lz indexer
- Moved logic for `__getitem__` into a method called `_get` which accepts a `materialize` argument.
=> Add lazy indexing functionality, e.g. `dp.lz[0:3]`

mosaic/columns/abstract.py, mosaic/datapanel.py, mosaic/mixins/inspect_fn.py, mosaic/mixins/mapping.py, mosaic/mixins/materialize.py, mosaic/tools/utils.py, tests/mosaic/test_datapanel.py, tests/testbeds.py
Other changes:
- Fix bug in update case when `visible_rows` is not `None` 
- Expand coverage of update tests to catch the bug above
=> Add support for lazy `map`, `update` and `filter` through `materialize` arg

mosaic/columns/abstract.py, mosaic/datapanel.py, tests/mosaic/test_datapanel.py
Other changes:
- Fix bug in AbstractColumn on empty index slices e.g. col[:0]
- Encapsulate `visible_columns`, so that we can enforce that "index" is always visible.
=> Implement `head` and `tail` for `DataPanel` and columns

mosaic/datapanel.py, tests/mosaic/test_datapanel.py, tests/testbeds.py
Update no longer relies on `_merge_batch_and_output`. Before,  if `input_columns` and `visible_rows` were both not `None`, `update` wouldn't keep the rows not in `input_columns`. To address this, we simplify update to now simply generate a copy of the datapanel and add a row.
Other changes: 
- Address issue where all columns (not just visible columns) were used if `input_columns=None`
=> Simplify `DataPanel.update` and add tests for update

mosaic/columns/abstract.py, mosaic/columns/list_column.py, mosaic/datapanel.py, mosaic/mixins/copying.py, mosaic/ops/merge.py, tests/mosaic/ops/test_merge.py
For very large DataPanels, filters and merges are very slow. This is because our current copy, actually copies the underlying data. Now, lazy indexing returns a view of the original column, without copying the underlying data using the `view` method, which is part of the copy mixin. 
Other related changes for speedup:
- Remove the list index for each column
- Updated `translate_index` to not create a np.arange for some types of indexes – still need to do this for all types of indexes and left some TODOs
Other fixes of merge:
- in `merge`, `check_merge_columns` assumes list inputs. If left_on or right_on is string, it fails.  move the check to after you cast to lists.
-  The join column gets cast into a numpy array rather than staying what it was before. So if a join column was a …
=> Add method `view` for getting new Column with the same underlying data

mosaic/__init__.py, mosaic/columns/abstract.py, mosaic/columns/cell_column.py, mosaic/columns/list_column.py, mosaic/columns/numpy_column.py, mosaic/columns/tensor_column.py, mosaic/datapanel.py, mosaic/errors.py, mosaic/ops/concat.py, tests/mosaic/ops/test_concat.py, tests/mosaic/test_datapanel.py, tests/testbeds.py
Add implementation of concat for DataPanel and core columns. Note: this does not work for speciality columns that haven't implemented `concat`. TODO: create a "composed column" which we can use for a default output of concat. 
Other changes:
- Whether `data` property shows invisible rows is inconsistent across different column types. Make all columns return only visible rows
- Add tests for concatenate
=> Implement `mosaic.concat`

README.md, mosaic/columns/abstract.py, mosaic/contrib/wilds/__init__.py, mosaic/datapanel.py, mosaic/mixins/inspect_fn.py, mosaic/mixins/mapping.py, mosaic/ops/concat.py, tests/mosaic/columns/test_numpy_column.py, tests/mosaic/columns/test_tensor_column.py, tests/mosaic/test_datapanel.py
Rename `batched` to `is_batched_fn` to more clearly indicate to the user that the flag is referring to whether the function is batched or not.
=> rename batched -> is_batched_fn

mosaic/columns/prediction_column.py, mosaic/columns/tensor_column.py, tests/mosaic/columns/test_tensor_column.py
This PR adds support for `torch.XX` ops:
Resolves #47
=> Bug fix: Add support for torch ops on TensorColumn

mosaic/tools/lazy_loader.py
Adds an additional `error` argument to `LazyLoader` that allows users to give instructions to users when the import leads to an `ImportError`.
=> Add optional ImportError text to LazyLoader

mosaic/datapanel.py, mosaic/mixins/mapping.py, mosaic/ops/concat.py, mosaic/ops/merge.py, mosaic/pipelines/entitydatapanel.py, mosaic/provenance.py, mosaic/tools/lazy_loader.py, tests/mosaic/test_datapanel.py
When datapanels are subclasses, ops on these datapanels (__getitem__, merge, append, etc) returned instances of `mosaic.DataPanel` instead of the subclass type
All class methods can be called from the instance. This will automatically pass the type of the instance (e.g. subclass) to the class method. For example,
```python
import mosaic as ms
class DataPanelSubclass(ms.DataPanel):
pass
dp = DataPanelSubclass(...)
dp.from_batch(...)  # called with cls=DataPanelSubclass
```
When `from_batch` is used from instance methods, we call `self.from_batch` instead of `DataPanel.from_batch`.
By calling `self.from_batch`, the initializer of the **subclass** is called as `from_batch` calls `cls(...)`. This can be an issue if there is state in the current instance (e.g. `self`) that needs to be passed …
=> bug fix: have ops on subclassed datapanels return subclass type

mosaic/__init__.py, mosaic/columns/embedding_column.py, mosaic/columns/prediction_column.py, mosaic/columns/tensor_column.py, mosaic/datapanel.py, mosaic/mixins/cloneable.py, mosaic/mixins/mapping.py
=> Use cloneable design pattern to fix mmap and general mapping with complex column types

meerkat/columns/prediction_column.py, tests/mosaic/columns/test_prediction_column.py
Fix logic for prediction column not having correct number of classes. Note `0` is treated as a class index, so number of classes are `max(pred) + 1`
Closes #92
=> Bugfix: PredictionColumn does the have correct number of classes

meerkat/block/manager.py, meerkat/datapanel.py, tests/meerkat/block/test_manager.py
- Calls `rmtree` on old column and block directories when writing a block manager to the same directory as a previous block manager
- Add tests for this functionality
- closes #127
=> Support overwriting old manager when writing

meerkat/columns/cell_column.py
Cannot clone when materialize is true because the data could change types. This is the same as what we had to do for LambdaColumn
=> Fix issue where cell column materialize returns a cell column

meerkat/logging/utils.py, tests/meerkat/logging/test_utils.py
Issue #177 highlights how users without write permissions on `/tmp` will not be able to import meerkat. 
With this PR, meerkat tries a few potential logging directories (/tmp, users home directory). Only if none of them work will a PermissionError be raised.
Also, we can now manually specify a log dir via the `MEERKAT_LOG_DIR` environment variable. The PermissionError that we raise if none of the defaults work instructs the user to set the environment variable `MEERKAT_LOG_DIR` to some directory they have write access to.
=> Make logging initialization robust to permissions 

meerkat/mixins/io.py
Co-authored-by: Jesse Vig <45317205+jessevig@users.noreply.github.com>
@krandiash enable this code to run without errors:
```
import meerkat as mk
import spacy
nlp = spacy.load("en_core_web_sm")
doc1 = nlp("Apple is looking at buying U.K. startup for $1 billion")
doc2 = nlp("Hello there")
dp = mk.DataPanel({
'list': [{}, {}]
})
dp.write('meerkat.dataset')
dp2 = dp.read('meerkat.dataset', nlp=nlp)
```
=> Add args, kwargs to ColumnIOMixin._read_data

meerkat/columns/tensor_column.py, meerkat/datapanel.py, setup.py, tests/meerkat/test_datapanel.py
Closes issue raised in #213. 
Simplified `to_jsonl` to simply wrap `to_pandas`, which addressed the issue.
=> Fix issue where arraycolumns can't be saved with jsonlines

meerkat/columns/lambda_column.py, meerkat/columns/list_column.py
=> Fix PIL attribute error on list and lambda column representations

meerkat/contrib/audioset.py, meerkat/mixins/cloneable.py
Utility functions for loading AudioSet dataset into Meerkat DataPanel.
=> Audioset DataPanel

meerkat/block/manager.py, meerkat/columns/audio_column.py, meerkat/columns/file_column.py, meerkat/columns/image_column.py, meerkat/contrib/audioset.py, meerkat/contrib/inaturalist.py, meerkat/mixins/cloneable.py, meerkat/tools/utils.py
Because block_ref groups with only a single block_ref are not consolidated, sometimes when writing datapanels, we would write unnecessary data not actually in the datapanel.
=> Make write only write columns in datapanel

meerkat/env.py, meerkat/interactive/api/routers/endpoint.py, meerkat/interactive/api/routers/page.py, meerkat/interactive/api/routers/store.py, meerkat/interactive/graph/store.py, meerkat/interactive/utils.py, tests/meerkat/interactive/test_util.py
On some Linux machines, encoding of stores was not working.
This may be because the json encoding was not recursive. `Store.to_json()` returned the wrapped object. If the encoding was recursive, the encoding would have been applied to the wrapped object. If it is not recursive, `iter` was called on the store object, which would fail.
Have `Store.to_json` return the json encoded object in a recursive way.
Verified the issue was fixed on a Ubuntu 22.04 machine
- Add utilities for managing packages and environment information in meerkat
=> bugfix: json encoding of stores

meerkat/datasets/__init__.py, meerkat/datasets/lra/__init__.py, meerkat/datasets/lra/pathfinder.py, meerkat/datasets/wilds/__init__.py, meerkat/ops/merge.py
Add LRA Pathfinder dataset to meerkat.
To avoid tensorflow dependencies, we have preprocessed the dataset. The preprocessed dataset is fetched with meerkat
Reference:
https://github.com/google-research/long-range-arena
=> add pathfinder dataset

.github/workflows/ci.yml
The CI is downloading ipython=8.13 even for python 3.8, which is not supported
pin the version in the CI to skirt this issue, for now
=> Pin jupyter==8.12 in linting ci

.github/workflows/ci.yml, .github/workflows/gh-pages.yml, .readthedocs.yml, docs/requirements.txt, setup.py
This is a known bug and a merge is underway:
https://github.com/ipython/ipython/pull/14054
This is a temporary solution until the ipython version is yanked
=> `ipython=8.13` is installed for python=3.8 though its not supported

setup.py
To bump the version, use
```bash
python setup.py bumpversion --version <version>
```
This will bump the python and npm versions, commit the changes to a new branch `bumpversion/v<version>`, and push the changes to github.
The user will be responsible for opening a PR from the branch to main
=> Bumpversion utility
