HazyResearch/meerkat

.github/workflows/ci.yml
setup.py

- Update `wilds` optional dependencies
- Don't install `wilds` in the CI (slow)

Update CI and setup.py

---

mosaic/columns/embedding_column.py
mosaic/datapanel.py

Other changes:
- Remove `faiss` from type hint, so it is not required

Add `from_csv` to DataPanel

---

README.md
mosaic/__init__.py
mosaic/columns/abstract.py
mosaic/columns/cell_column.py
mosaic/columns/image_column.py
mosaic/columns/list_column.py
mosaic/datapanel.py
mosaic/mixins/copying.py
mosaic/mixins/inspect_fn.py
mosaic/mixins/visibility.py
setup.py
tests/mosaic/columns/test_numpy_column.py
tests/mosaic/test_datapanel.py

Other changes:
- Add `_repr_pandas_` to `CellColumn`
- Add `__setitem__` to `ListColumn`
- Fix issue where a filter that returns a `NumpyArrayColumn` of bool is not recognized as a bool return type
- Fix issue where setting `visible_rows` on a datapane that already has `visible_rows != None` leads to an exception
- Fix issue where hidden columns don't have their `visible_rows` updated when setting `visible_rows`
- Add filter test to `test_datapanel`
- Add filter test to `test_numpy_column`

Add `ImageColumn`, test filter, fix visibility

---

mosaic/datapanel.py
setup.py
tests/mosaic/test_datapanel.py

Json->Ujson
Test
Creating dict of data while reading rather than reading in all data to list, then doing json transpose

Added ujson smarter loading to datapanel

---

mosaic/datapanel.py
tests/mosaic/test_datapanel.py

bug fix: DataPanel.from_csv did not return the datapanel

---

mosaic/columns/abstract.py
mosaic/datapanel.py
mosaic/mixins/mapping.py

Other changes:
- Change `pbar` to be False by default
- Change `num_workers` to be 0 by default

Make progress bars optional with `pbar` argument

---

mosaic/__init__.py
mosaic/columns/abstract.py
mosaic/columns/list_column.py
mosaic/columns/numpy_column.py
mosaic/columns/tensor_column.py
mosaic/datapanel.py
mosaic/errors.py
mosaic/mixins/inspect_fn.py
mosaic/mixins/visibility.py
mosaic/ops/merge.py
tests/mosaic/ops/test_merge.py
tests/mosaic/test_datapanel.py
tests/testbeds.py

Other changes:
- Implement `append` for DataPanel
- Remove `visible_rows` from `DataPanel`
- Added default support for __setitem__ to `AbstractColumn` 
- Addressed some deprecation warnings

Implement `DataPanel` merge operation

---

README.md

Modified ImageColumn(...) to ImageColumn.from_filepaths(...) in the demo code of README.

ImageColumn README fix

---

mosaic/columns/prediction_column.py
mosaic/mixins/copying.py
tests/mosaic/columns/test_prediction_column.py

- Adding `ClassificationOutputColumn` to handle classification related logic

adding classification output column

---

mosaic/columns/tensor_column.py
mosaic/datapanel.py
tests/mosaic/test_datapanel.py

Other changes:
- Swap tensor copy construct with .clone to suppress warning

Make `columns` return `visible_columns`

---

mosaic/columns/abstract.py

Fix bug where non-image cells get converted to an ImageColumn.

Fix `from_data` in abstract column

---

mosaic/mixins/device.py

Adds a `DeviceMixin` that can be added to any class to initialize a device.

Add `DeviceMixin`

---

mosaic/mixins/device.py

Changes the import to `typing`

Fix DeviceMixin typing error 

---

mosaic/columns/abstract.py
mosaic/datapanel.py

`.streamlit()` methods to display DataPanels in Streamlit

Add methods for streamlit display

---

meerkat/columns/pandas_column.py

Fix pandas string accessor import issue on old versions

---

meerkat/contrib/torchvision/__init__.py

- Add a folder for torchvision contrib
- Add `get_cifar10` function that returns CIFAR10 as a `DataPanel`

Add CIFAR10 DataPanel

---

meerkat/columns/abstract.py
meerkat/columns/numpy_column.py
meerkat/datapanel.py
meerkat/pipelines/entitydatapanel.py
tests/meerkat/pipelines/test_entitydatapanel.py
tests/meerkat/test_datapanel.py

Other changes:
- Make default str column type a PandasColumn

Add support for missing values when constructing from list of dicts

---

meerkat/block/manager.py
meerkat/block/pandas_block.py
meerkat/columns/abstract.py
meerkat/columns/cell_column.py
meerkat/columns/image_column.py
meerkat/columns/lambda_column.py
meerkat/columns/list_column.py
meerkat/columns/numpy_column.py
meerkat/columns/pandas_column.py
meerkat/columns/tensor_column.py
meerkat/config.py
meerkat/contrib/mimic/reports.py
meerkat/datapanel.py
setup.py
tests/meerkat/columns/abstract.py
tests/meerkat/columns/test_image_column.py
tests/meerkat/test_datapanel.py

Closes #111 
Other changes:
- Add support for visualizing images in Jupyter notebook, closes #148

Implement faster display that doesn't convert entire DataPanel to pandas

---

meerkat/datapanel.py
tests/meerkat/test_datapanel.py

Add support for shuffling during batch

---

examples/eeg_data_demo.ipynb
meerkat/contrib/eeg/__init__.py
meerkat/contrib/eeg/data_utils.py

In this commit, I changed the `eeg` column to `eeg_input` which is now a lambda column for more efficient data access.

Make EEG column based on lambda

---

meerkat/contrib/registry.py
tests/meerkat/contrib/test_registry.py

Also add test module for registry with some very basic tests
Closes: #178

Add support for datasets.names and datasets.catalog

---

meerkat/contrib/celeba.py
meerkat/datapanel.py
meerkat/mixins/io.py
meerkat/tools/utils.py
tests/meerkat/mixins/test_io.py

Add meerkatloader for loading meerkat modules from yaml file

---

meerkat/block/manager.py
meerkat/columns/spacy_column.py
meerkat/datapanel.py
setup.py

Update `BlockManager` and `DataPanel` read to pass kwargs. Update Spacy column to match new Meerkat column methods.

Update Spacy column 

---

meerkat/block/tensor_block.py

Fix issue where tensor columns can't be indexed with pandas series

---

meerkat/datapanel.py
tests/meerkat/test_datapanel.py

Fix from_huggingface and add tests

---

meerkat/datapanel.py

mmap path was not being passed into map

mmap path bug fix

---

meerkat/datapanel.py
tests/meerkat/test_datapanel.py

- Returns Set instead of dictionary
- Add check in subclass tests to make sure it's possible to add new _state_keys
Closes #223

Fix issue with subclassing `DataPanel._state_keys`

---

.github/workflows/ci.yml
docs/source/guide/slicing.rst
meerkat/__init__.py
meerkat/columns/abstract.py
meerkat/columns/audio_column.py
meerkat/columns/file_column.py
meerkat/columns/image_column.py
meerkat/columns/lambda_column.py
meerkat/columns/list_column.py
meerkat/config.py
meerkat/contrib/registry.py
meerkat/contrib/torchaudio/__init__.py
meerkat/display.py
setup.py
tests/meerkat/columns/test_audio_column.py
tests/meerkat/columns/test_file_column.py
tests/meerkat/columns/test_image_column.py
tests/meerkat/test_display.py

Move most of the implementation of `ImageColumn` into a parent class `FileColumn`, which is now shared with `AudioColumn`. 
Also added the formatter property to abstract columns so that the representation of a column isn't tied only to its column type and can be modified.

Add support for AudioColumn

---

meerkat/contrib/audioset.py

Make AudioSet DataPanels relational

---

meerkat/columns/abstract.py
meerkat/columns/object/base.py
meerkat/dataframe.py
meerkat/datasets/coco/__init__.py
meerkat/datasets/lvis/__init__.py
meerkat/mixins/reactifiable.py
tests/meerkat/columns/object/test_base.py

- Add `__array__` for faster conversion to numpy array
- Add `_set_data` to the list of functions to skip making reactive

Optimize dataframe construction

---

docs/source/index.md

Fix blog link

---

.github/workflows/publish.yml
setup.py

- Add guard to only run bumpversion from `main` branch
- Add npm publishing to publish.yml workflow
- Add auto git tagging to publish.yml workflow

Update Autopush CI

---

meerkat/ops/complete.py

fix mk complete to not use hardcoded client and cache connections
